export default {
  dot: 'dot-circle',
  trash: 'trash-alt',
  prev: 'angle-left',
  house: 'home',
  clock: 'clock',
  settings: 'cogs',
  person: 'user',
  circle: 'circle',
  next: 'angle-right',
  page: 'file-alt',
  chevronRight: 'chevron-right',
  burgerButton: 'bars',
  close: 'times-circle',
};
