export default {
  dot: 'dot-circle',
  trash: 'trash-alt',
  prev: 'angle-left',
  house: 'home',
  clock: 'clock',
  settings: 'cogs',
  person: 'user',
  circle: 'circle',
  next: 'angle-right',
  page: 'file-alt',
  chevronRight: 'chevron-right',
  burgerButton: 'bars',
  close: 'times-circle',
  checkMarkCircle: 'check-circle',
  checkMarkSquare: 'check-square',
  arrowDown: 'angle-down',
  arrowCircleDown: 'chevron-circle-down',
  arrowCircleUp: 'chevron-circle-up',
  external: 'external-link-alt',
  crossError: 'times-circle',
  hourglass: 'hourglass-half',
  skippArrows: 'angle-double-right',
};
